on:
  workflow_call:
    inputs:
      dev_workspace:
        description: Then name of the dev Terraform Cloud workspace
        required: true
        type: string
      prod_workspaces:
        description: The list of Terraform Cloud prod workspace names separated by comma
        required: false
        type: string
      variables:
        description: Terraform Cloud variables which will be applied to each workspace
        required: true
        type: string
    secrets:
      TF_API_TOKEN:
        required: true

jobs:
  deploy_dev:
    name: Deploy in ${{ inputs.dev_workspace }} workspace
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: development
    steps:
    - name: Create Terraform Cloud run
      uses: neuro-inc/terraform-cloud-run-action@v24.7.0
      with:
        token: ${{ secrets.TF_API_TOKEN }}
        workspace: ${{ inputs.dev_workspace }}
        variables: ${{ inputs.variables }}

  deploy_prod:
    name: Deploy in ${{ matrix.workspace }} workspace
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    needs: deploy_dev
    if: ${{ inputs.prod_workspaces != '' }}
    strategy:
      matrix:
        workspace: '[${{ inputs.prod_workspaces }}]'
    steps:
    - name: Create Terraform Cloud run
      uses: neuro-inc/terraform-cloud-run-action@v24.7.0
      with:
        token: ${{ secrets.TF_API_TOKEN }}
        workspace: ${{ matrix.workspace }}
        variables: ${{ inputs.variables }}
