---
# Release Service 'Called workflow'
# Publishes Neu.ro service as ghcr.io Docker image and Helm Chart,
# Create a github release with linked issues and pull requests

on:
  workflow_call:
    inputs:
      helm_charts:
        description: A space-separated list of helm charts
        required: true
        type: string
      version:
        description: Helm chart version to deploy
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  release:
    name: Deploy on dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout commit
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.14.0
    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/86382326153/locations/global/workloadIdentityPools/githubpool/providers/github     
        service_account: github-dev@development-421920.iam.gserviceaccount.com
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        install_components: gke-gcloud-auth-plugin
    - name: Update kube config
      run: gcloud container clusters get-credentials dev -z us-central1-a
    - name: Deploy to kubernetes
      run: |
        echo $CR_TOKEN | helm registry login ghcr.io -u x-access-token --password-stdin
        for HELM_CHART in $CHARTS; do
          helm upgrade $HELM_CHART \
            oci://ghcr.io/neuro-inc/helm-charts/$HELM_CHART \
            --version ${{ inputs.version }} \
            -f charts/$HELM_CHART/values-dev.yaml \
            --namespace platform --install --wait --timeout 600s
        done
      env:
        CHARTS: ${{ inputs.helm_charts }}
        CR_TOKEN: ${{ github.token }}
